project_id = "sjrlfwxfojfyzujulyas"

[functions.ai-product-recommendations]
verify_jwt = false

[functions.send-order-confirmation]
verify_jwt = false

[functions.process-payment]
verify_jwt = false

[functions.inventory-alert]
verify_jwt = false

[functions.paypal-create-order]
verify_jwt = false

[functions.paypal-capture-order]
verify_jwt = false

[functions.mercadopago-create-preference]
verify_jwt = false

[functions.mercadopago-get-payment]
verify_jwt = false

[functions.mercadopago-webhook]
verify_jwt = false